### ISSUE TITLE
Intermittent failure in one output of CPU inference

### ISSUE THREAD

**Issue by wphicks** [triton-inference-server/fil_backend#104]
```
Starting tests of model xgboost-cpu without visible GPU...
Performance statistics for xgboost-cpu:
Random seed value: 111245
Traceback (most recent call last):
  File "/triton_fil/qa/L0_e2e/test_model.py", line 608, in <module>
    run_test(
  File "/triton_fil/qa/L0_e2e/test_model.py", line 483, in run_test
    np.testing.assert_almost_equal(
  File "/root/miniconda3/envs/triton_test/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 583, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/root/miniconda3/envs/triton_test/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1046, in assert_array_almost_equal
    assert_array_compare(compare, x, y, err_msg=err_msg, verbose=verbose,
  File "/root/miniconda3/envs/triton_test/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 3 decimals
Mismatched elements: 1 / 128 (0.781%)
Max absolute difference: 2.
Max relative difference: 1.
 x: array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,...
 y: array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,...
```

We might want to loosen up the test slightly by allowing a small percentage of failures in classification output for CPU vs GPU evaluation. @hcho3 any thoughts on what makes sense here?

**Comment by hcho3** [comment]
A better fix would be to use probability outputs for this model and then allow for a small error. Right now, we don't know whether the wrong class output is due to a slight difference (50.4% vs 49.6%, let's say) or due to a significant difference (80% vs 20%).

**Comment by hcho3** [comment]
Let me try to reproduce it.

**Comment by hcho3** [comment]
I was able to reproduce the error, by setting the random seed to 111245. I will investigate a possible fix.

**Comment by hcho3** [comment]
@wphicks #105 fixes the particular test, by comparing probability outputs rather than class outputs.

**Comment by wphicks** [comment]
Going to move this to a 21.08 issue, though the Treelite changes may push it to 21.09. In fact, I think that would probably be preferable, but I'll leave it on the 21.08 board in case this problem gets less intermittent. See #105 for additional context.
